# Generated by Django 3.2.4 on 2021-06-27 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0002_auto_20210626_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='user_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
