# Generated by Django 3.2.4 on 2021-07-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0003_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='shuffled',
            field=models.BooleanField(default=False),
        ),
    ]
