# Generated by Django 3.2.4 on 2021-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0006_auto_20210703_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='reshuffled',
            field=models.BooleanField(default=False),
        ),
    ]
