# Generated by Django 3.2.4 on 2021-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0007_group_reshuffled'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='reshuffled_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='reshuffled_before',
            field=models.IntegerField(default=0),
        ),
    ]
