# Generated by Django 3.2.4 on 2021-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0009_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='group',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
