# Generated by Django 3.2.4 on 2021-07-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0010_alter_alert_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='group',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
