# Generated by Django 3.2.4 on 2021-07-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0011_alter_alert_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image_url',
            field=models.URLField(default='google.com'),
        ),
    ]
