# Generated by Django 3.2.4 on 2021-07-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0012_gift_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_like', to='secretsanta.group'),
        ),
    ]
