# Generated by Django 3.2.4 on 2021-07-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0014_auto_20210707_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
