# Generated by Django 3.2.4 on 2021-07-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0015_alter_wishlist_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='address',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='interest',
        ),
    ]
