# Generated by Django 3.2.4 on 2021-07-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0016_auto_20210708_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='reshuffled',
        ),
        migrations.RemoveField(
            model_name='group',
            name='reshuffled_after',
        ),
        migrations.RemoveField(
            model_name='group',
            name='reshuffled_before',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
